Sarray = zeros(1000,1000);
Iarray = zeros(1000,1000);
Rarray = zeros(1000,1000);
timestep = 0.00001;
[Sarray(1,:),Iarray(1,:),Rarray(1,:)] = DeltaSIRDDFT(S, ...
                                                     I, ...
                                                     R, ...
                                                     Di, ...
                                                     Csi, ...
                                                     Cres, ...
                                                     CgammaI, ...
                                                     Ds, ...
                                                     Dr, ...
                                                     Cc, ...
                                                     Cw, ...
                                                     Cm, ...
                                                     CgammaS, ...
                                                     CgammaR, ...
                                                     dx, ...
                                                     matConv);
Sarray(1,:) = Sarray(1,:) + S;
for i = 2:1000
    [DS,DI,DR] = DeltaSIRDDFT(Sarray(i-1,:),Iarray(i-1,:),Rarray(i-1,:), Di, Csi, Cres, CgammaI, Ds, Dr, Cc, Cw, Cm, CgammaS, CgammaR, dx, matConv);
    Sarray(i,:) = Sarray(i,:) + (DS * timestep);
    Iarray(i,:) = Iarray(i,:) + (DI * timestep);
    Rarray(i,:) = Rarray(i,:) + (DR * timestep);
end